apiVersion: v1
kind: PersistentVolume
metadata:
  name: combats-mysql-disk
  labels:
    name: combats-mysql-disk
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: "combats-mysql-disk"
    fsType: "ext4"