kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol1
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/aclawson/kube/vol1"

