UNITS = {
    'Rats': ['Ratlings', 'Rats', 'Diseased Rats', 'Elder Bucks'],
    'Wild Dogs': ['Pups', 'Wild Dogs', 'Rabid Hounds', 'Pack Leaders'],
    'Giant Scuttlers': ['Scuttlers', 'Adult Scuttlers', 'Elder Scuttlers','Ravenous Scuttlers'],
    'Simien Wolves': ['Adolescent Wolves', 'Adult Wolves', 'Snarling Wolves', 'Simien Wolfpack Leaders'],
    'Brown bears': ['Bear Cubs', 'Adolescent Grizzlies', 'Enraged Kodiaks', 'Adult Grizzlies'],
    'Spiders': ['Spitting Spiders', 'Giant Spiders', 'Adolescent Giant Spiders'],
    'Wolves': ['Wolfpups', 'Grey Wolves', 'White Wolves', 'Alpha Wolves'],
    'Scaled Chargers': ['Scaled Chargers', 'Armoured Chargers', 'Heavy Chargers', 'Lightning Chargers'],
    'Salamanders': ['Small Salamanders', 'Large Salamanders', 'Spitting Salamanders'],
    'Pumas': ['Adolescent Pumas', 'Wiry Pumas', 'Muscular Pumas'],
    'Siege engines': ['Ballistas', 'Catapults', 'Mangonels', 'Trebuchets'],
    'Wall engines': ['Battering Rams', 'Battery-towers', 'Tortoises'],
    'Cavalry': ['Runeriders', 'Packsmen', 'Marshals', 'Death Packs', 'Swiftsteeds', 'Knights', 'Charioteers', 'Wolfriders'],
    'Infantry': ['Stalwarts', 'Axemen', 'Fangs', 'Fists', 'Men-At-Arms', 'Swordsmen', 'Wardens', 'Wardancers'],
    'Spears': ['Halbardiers', 'Protectors', 'Clan Guardsmen', 'Pikemen', 'Yeomen', 'Phalanxes', 'Militiamen'],
    'Bows': ['Slingers', 'Crossbowmen', 'Elven Trueshots', 'Sentinels', 'Archers', 'Longbowmen', 'Clanguards', 'Death Dealers'],
}