apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: combats-update
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      name: combats-update
      labels:
        app: combats-update
        tier: frontend
    spec:
      containers:
      - name: combats-update
        image: gcr.io/strategos-151306/combats-upd-daemon:0.1.0
        env:
        - name: COMBATS_DB_HOST
          value: combats-mysql
        - name: COMBATS_DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        - name: UPDATE_TIMER
          value: "300"
        ports:
        - containerPort: 5000
          name: combats
